repos:
  # 1. Standard-Prüfungen (Formatierung, Whitespaces, sichere Dateien)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: detect-private-key

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.59.1
    hooks:
      - id: golangci-lint
        args: [--timeout=5m]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.16.4
    hooks:
      - id: commitizen
        args: ["-l", "0", "--commit-msg-file"]
